smzair/DAM

app/Http/Controllers/ClientUserManagementController.php, app/Models/User.php, resources/views/admin/Control-panel/clients-user-list.blade.php, resources/views/layouts/admin.blade.php, routes/web.php
View all sub users to Admin and Super admin
=> Control panel for admin and super admin.

app/Http/Controllers/ClientUserManagementController.php, app/Http/Controllers/UserAssetsController.php, resources/views/clients/ClientAssets/client-user-Creative-lots.blade.php, resources/views/clients/ClientAssets/client-user-shoot-lots.blade.php
Shoot Lots page redirect to file manger for file download with activity logs.
=> Your assets Activity log-

.gitignore, app/Http/Controllers/EditingClientFileManagerController.php, app/Http/Controllers/clientFileManager.php
-Shoot Raw images Download Activity Logs and Shoot Edited images Download Activity Logs
=> File Manager Activity Logs

app/Helpers/Helpers.php, app/Http/Controllers/ClientsControllers/User_Assets_Favorites_controller.php, app/Models/ClientsModel/FavoriteAsset.php, resources/views/clients/ClientAssetsLinks/your-assets-Favorites.blade.php, resources/views/layouts/DamNewMain.blade.php
YOUR ASSETS -> Files and links Add to Favourites (Lot,wrc,sku and etc) code live in c-panel. Done.
YOUR ASSETS -> Favourites.
-List out all added Favourites module (Lots, wrcs, skus,images and etc). Ongoing
-Editing added Favourites Images ( Raw image and Edited Images), Done.
-Shoot added Favourites Images ( Raw image and Edited Images), pendding (fetching issue).
Shoot added Favourites Lots List, Done
Editing added Favourites Lots List, Done
Cataloging added Favourites Lots List, Done
Creative added Favourites Lots List, Done
Shoot added Favourites Raw Skus, Done
Shoot added Favourites Edited Skus, Done
Shoot lot wrc. pendding
Editing lot wrc. pendding
=> List out all added Favourites data (Lot, Wrc, etc) 05-06-2023

app/Http/Controllers/ClientsControllers/User_Assets_Favorites_controller.php, app/Models/ClientsModel/FavoriteAsset.php, resources/views/clients/ClientAssetsLinks/your-assets-Favorites.blade.php
/*Add on New Changes */
Saprate Favariots Lots
-Shoot & Post-production Lots
-Marketing Creative & Listing Lots
Favariots List.
-Validation based on User. Done
=> Add on New Changes, Saprate Favariots Lots And Validation based on User

app/Helpers/Helpers.php, app/Http/Controllers/ClientsControllers/ClientDashboardControllerNew.php, app/Http/Controllers/ClientsControllers/User_Assets_Controller.php, app/Http/Controllers/ClientsControllers/User_Assets_links_controller.php, app/Models/EditorLotModel.php, app/Models/Lots.php, resources/views/clients/ClientAssets/your_assets_files.blade.php, resources/views/clients/ClientAssetsLinks/your-assets-Links-Lots.blade.php, resources/views/clients/Timeline/catlogTimeline_New.blade.php, resources/views/clients/Timeline/creativeTimeline_New.blade.php, routes/web.php
-Changes in sort functionality in Track Lots. Done.
-Track lots Status changes
-Shoot lots Status changes in Lots and its full details. Done.
-Editing Lots status changes in lots and its Full details. Done.
-Creative lots Status changes in Lots and its full details. Done.
-Cataloging lots Status changes in Lots and its full details. Done.
-In shoot lots progress is 60% (shoot started) but Showing Editing & QC Done , Issue resolved.
-Track lots Remove  Download invoice And  Invoice Number from view detail tables and pages. Done.
Your Assets
-Changes in sort functionality in Your Assets Files. Done.
-Changes in sort functionality in Your Assets Links. Done.
=> Sorting functionality And Changes in Lots Status.

app/Http/Controllers/ClientsControllers/ClientCommonController.php, app/Http/Controllers/ClientsControllers/User_Assets_Controller.php, app/Jobs/SearchDataCollection.php, app/Models/CreatLots.php, app/Models/EditorLotModel.php, app/Models/Lots.php, app/Models/LotsCatalog.php, resources/views/clients/ClientAssets/your_assets_files_editing_uploaded_images.blade.php, resources/views/clients/ClientAssets/your_assets_shoot_skus_uploaded_files.blade.php, resources/views/clients/gloableSearchNew.blade.php
Global search changes,
Shoot Wrcs
Post-production Wrcs
Post-production Wrcs
Listing Wrcs
Shoot Lots
Post-production Lots
Post-production Lots
Listing Lots
also search lot, wrc created date in DD-MM-YYYY format
=> Gloable serach changes, Lots, Wrc for all services

public/css/dam_new_style_odn.css, resources/views/clients/ClientDashboardDam.blade.php, resources/views/clients/Timeline/catlogTimeline_New.blade.php, resources/views/clients/Timeline/creativeTimeline_New.blade.php, resources/views/clients/Timeline/editorLotTimeline_New.blade.php, resources/views/clients/Timeline/editorShootTimeline_New.blade.php
Track Lots Changes file download from online upto 30-06-23
=> Track Lots Changes file download from online upto 30-06-23

app/Http/Controllers/CatalogSubmissionController.php, app/Models/CatalogSubmission.php, app/Models/EditingSubmission.php, resources/views/submission/Editing-Ready-For-Submission.blade.php, resources/views/submission/catalog-submission.blade.php
creative Admin panel Online changes for catalog ready for submission and Editing ready for submission
=> Creative Panel Online Changes for submission

resources/views/clients/Timeline/editorLotTimeline_New.blade.php, resources/views/clients/Timeline/editorShootTimeline_New.blade.php
New Task - 
Changes In Track lots timeline, for Editing and Shoot
-Give an option for Download all assets based on conditions.
conditions - If all wrcs are submitted then show Download all assets Button , otherwise hidden,
In Wrc List, changes in image column, If wrc submitted then show Download Image button otherwise it will be blank.
=> Changes In Track lots timeline, for Editing and Shoot

app/Http/Controllers/CatalogAllocationController.php, app/Http/Controllers/CatalogWrcController.php, app/Http/Controllers/creativeWrc.php, app/Models/EditingWrc.php, resources/views/clients/ClientAssetsLinks/your-assets-Links-Lots.blade.php
Send Notification to Dam.
-Create Catalog WRC, Done.
-Create Editing WRC, Done.
-Create Creative WRC, Done.
-Create Catalog Allocation (Planning) , Done.
=> Send Notification to users when creating Wrc, other activits happend.

app/Helpers/Host.php, app/Http/Controllers/ClientsControllers/ClientCommonController.php, app/Http/Controllers/ClientsControllers/ClientDashboardControllerNew.php, app/Models/Lots.php, public/css/dam_new_style_odn.css, resources/views/clients/Timeline/editorShootTimeline_New.blade.php, resources/views/layouts/DamNewMain.blade.php
Changes in Track lot, progress bar. Ongoing
-Change in Shoot lot timeline, progress bar, add new bar for invoice befor Submissions. Ui Done
-Change in Shoot lot timeline, progress bar, add new bar for invoice befor Submissions. Backend done.
-Changes in Track lots list for completed Lots due to new status invoice. Done.
=> Changes in Track lot

app/Http/Controllers/CatalogAllocationController.php, app/Http/Controllers/CatalogClientARController.php, app/Models/CatalogAllocation.php, app/Models/ClientActivityLog.php, app/Models/LotsCatalog.php, public/css/dam_new_style_odn.css, resources/views/Invoice/catalog-Invoice.blade.php, resources/views/clients/Timeline/catlogTimeline_New.blade.php
Changes in Track lot, progress bar. Ongoing
-Change in Listing (Cataloging) lot timeline, progress bar, add new bar for invoice before Submissions. Ongoing
-Change in Listing (Cataloging) lot timeline, progress bar, add new bar for invoice before Submissions. Backend done.
-Changes in Track lots list for completed Listing (Cataloging) Lots due to new status invoice. Done.
-Testing Done from stating, like creating new commercial, lots, Wrc.
-After WRC creation allocate to user, and uploading by allocated user.
-Qc, then submission then client AR, After approval invoicing for WRC.
=> Changes in Track lot, progress bar for Listing (Cataloging) Lots

app/Helpers/Host.php, app/Http/Controllers/CatalogAllocationController.php, app/Models/CatalogAllocation.php, app/Models/CreatLots.php, app/Models/LotsCatalog.php, resources/views/clients/Timeline/catlogTimeline_New.blade.php, resources/views/clients/Timeline/creativeTimeline_New.blade.php
-Change in Creative lot timeline, progress bar, add new bar for invoice before Submissions. Done
-Change in Creative lot timeline, progress bar, add new bar for invoice before Submissions. Backend done.
-Changes in Track lots list for completed Creative Lots due to new status invoice. Done.
-Testing Done from stating, like creating new commercial, lots, Wrc.
-After WRC creation allocate to user, and uploading by allocated user.
-Qc, then submission then client AR, After approval invoicing for WRC.
=> Changes in progress bar for Creative Lots

app/Http/Controllers/CatalogLotsController.php, app/Models/NotificationModel/ClientNotification.php
Cataloging-
-Create Lots, Done.
-Create WRC, Done.
-Allocation (Planning) , Done.
-Wrc submission, Done
=> Send Notification to users (Cataloging)

app/Http/Controllers/CreativeAllocationController.php, app/Http/Controllers/CreativeSubmissionController.php, app/Http/Controllers/creativeLot.php, app/Models/CreativeAllocation.php
Creative Panel - done
-Create Lots, Done.
-Create WRC, Done.
-Allocation (Planning) , Done.
-Wrc submission, done
// ODN21072023-GBRNTN41  WRC GBRNCTI41-A
=> Send Notification to users ( Creative)

app/Http/Controllers/EditingUploadLinkController.php, app/Http/Controllers/ImageUploadController.php, app/Models/EditingAllocation.php, app/Models/EditorLotModel.php, app/Models/NotificationModel/ClientNotification.php, resources/views/Allocation/Editing_allocation.blade.php
Send Notification to Dam.
Editing Panel - done
-Create Lots, Done.
-Create WRC, Done.
-Allocation (Planning) , Done.
-Wrc submission, done
=> Send Notification to Dam. (Editing)

app/Http/Controllers/lotsController.php, app/Mail/Tatsos.php, app/Mail/WrcStatusUpdate.php, app/Mail/feedMail.php, app/Mail/feedbackMaIl.php, app/Mail/lotInfo.php, app/Mail/timeSheet.php, app/Mail/timeSheets.php
[Send Notification to Dam. Shoot Lot]
online file Download.
=> Send Notification to Dam. Shoot Lot

app/Http/Controllers/adminController-oldLocal.php
c-panel code download and , local file backup for 
adminController.php
=> c-panel code download and , local file backup

app/Http/Controllers/adminController.php, app/Models/NotificationModel/ClientNotification.php
Send Notification to Dam.
Shoot Panel - 
-Shoot Planning , Done.
=> Send Notification to Dam. Shoot planning

app/Http/Controllers/wrcController.php, app/Models/NotificationModel/ClientNotification.php, resources/views/Wrc/invoiceno.blade.php
Send notification to Dam,
Shoot Wrc invoice from Update WRC Invoice Number
=> Shoot Wrc invoice from Update WRC Invoice Number
